apiVersion: v1
kind: Service
metadata:
  name: svc-react-app
spec:
  selector:
    app: node-react-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
